[[redirects]]
  from = "/*"
  to = "/index.ejs"
  status = 200
  force = true

[build]
  base    = ""
  publish = "public"
  command = "npm run build" 

[build.environment]
  NPM_VERSION = "9.7.2"
  NODE_VERSION = "16.19.1"

[[plugins]]
  package = "netlify-plugin-ejs"
  [plugins.inputs]
    pattern = "**/*.ejs"